version: '3'
services:
  undetected-chromedriver:
    image: ultrafunk/undetected-chromedriver
    ports:
      - 5900:5900
    volumes:
      - ${PWD}/data:/data
    command: ipython /data/yourscript.py
